In [2]:
import csv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Data Preprocessing
- Removed unecessary columns and kept necessary data
- Replaced nulls with unkown

In [3]:
dataset = pd.read_csv("./NYPD_Shooting_Incident_Data__Year_To_Date_.csv")
dataset = dataset.drop(columns=["INCIDENT_KEY","OCCUR_DATE", "OCCUR_TIME", "JURISDICTION_CODE", "LOCATION_DESC", "X_COORD_CD", "Y_COORD_CD", "Longitude", "Latitude", "New Georeferenced Column", "Zip Codes", "Borough Boundaries", "City Council Districts", "Community Districts", "Police Precincts"])

dataset = dataset.replace({'(null)': None}) # change null into None so that we can remove
dataset = dataset.fillna("UNKNOWN") # Change Nulls into Unknown

print(dataset)

           BORO LOC_OF_OCCUR_DESC  PRECINCT LOC_CLASSFCTN_DESC  \
0         BRONX           OUTSIDE        49             STREET   
1         BRONX           OUTSIDE        52             STREET   
2         BRONX           OUTSIDE        44            VEHICLE   
3        QUEENS           OUTSIDE       113            HOUSING   
4      BROOKLYN            INSIDE        77           DWELLING   
...         ...               ...       ...                ...   
1711      BRONX           OUTSIDE        48             STREET   
1712  MANHATTAN           OUTSIDE        30             STREET   
1713  MANHATTAN           OUTSIDE        32             STREET   
1714      BRONX            INSIDE        46            HOUSING   
1715      BRONX           OUTSIDE        45             STREET   

     STATISTICAL_MURDER_FLAG PERP_AGE_GROUP PERP_SEX       PERP_RACE  \
0                          Y          18-24        M  BLACK HISPANIC   
1                          N          25-44        M  WHITE HIS

In [4]:
dataset.isnull().sum() # count amount of Null values


BORO                       0
LOC_OF_OCCUR_DESC          0
PRECINCT                   0
LOC_CLASSFCTN_DESC         0
STATISTICAL_MURDER_FLAG    0
PERP_AGE_GROUP             0
PERP_SEX                   0
PERP_RACE                  0
VIC_AGE_GROUP              0
VIC_SEX                    0
VIC_RACE                   0
dtype: int64

- Changing the Categorical data into numerical

In [17]:
from sklearn.preprocessing import OneHotEncoder

col_names = dataset.columns.values.tolist()
col_names.remove("PRECINCT")
print(col_names)

one_hot_encoded_data = pd.get_dummies(dataset, columns = col_names)
one_hot_encoded_data

['BORO', 'LOC_OF_OCCUR_DESC', 'LOC_CLASSFCTN_DESC', 'STATISTICAL_MURDER_FLAG', 'PERP_AGE_GROUP', 'PERP_SEX', 'PERP_RACE', 'VIC_AGE_GROUP', 'VIC_SEX', 'VIC_RACE']


PRECINCT  BORO_BRONX  BORO_BROOKLYN  BORO_MANHATTAN  BORO_QUEENS  \
0           49           1              0               0            0   
1           52           1              0               0            0   
2           44           1              0               0            0   
3          113           0              0               0            1   
4           77           0              1               0            0   
...        ...         ...            ...             ...          ...   
1711        48           1              0               0            0   
1712        30           0              0               1            0   
1713        32           0              0               1            0   
1714        46           1              0               0            0   
1715        45           1              0               0            0   

      BORO_STATEN ISLAND  LOC_OF_OCCUR_DESC_INSIDE  LOC_OF_OCCUR_DESC_OUTSIDE  \
0                      0                         0                          1   
1                      0                         0                          1   
2                      0                         0                          1   
3                      0                         0                          1   
4                      0                         1                          0   
...                  ...                       ...                        ...   
1711                   0                         0                          1   
1712                   0                         0                          1   
1713                   0                         0                          1   
1714                   0                         1                          0   
1715                   0                         0                          1   

      LOC_CLASSFCTN_DESC_COMMERCIAL  LOC_CLASSFCTN_DESC_DWELLING  ...  \
0                                 0                            0  ...   
1                                 0                            0  ...   
2                                 0                            0  ...   
3                                 0                            0  ...   
4                                 0                            1  ...   
...                             ...                          ...  ...   
1711                              0                            0  ...   
1712                              0                            0  ...   
1713                              0                            0  ...   
1714                              0                            0  ...   
1715                              0                            0  ...   

      VIC_AGE_GROUP_UNKNOWN  VIC_SEX_F  VIC_SEX_M  \
0                         0          1          0   
1                         0          0          1   
2                         0          0          1   
3                         0          0          1   
4                         0          1          0   
...                     ...        ...        ...   
1711                      0          0          1   
1712                      0          0          1   
1713                      0          0          1   
1714                      0          0          1   
1715                      0          0          1   

      VIC_RACE_AMERICAN INDIAN/ALASKAN NATIVE  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           0   
...                                       ...   
1711                                        0   
1712                                        0   
1713                                        0   
1714                                        0   
1715                                        0   

      VIC_RACE_ASIAN / PACIFIC ISLANDER  

### Feature Selection

In [18]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics

In [28]:
X = one_hot_encoded_data.iloc[:, :-1].values
y = one_hot_encoded_data.iloc[:, -1].values

print(X, y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

[[49  1  0 ...  0  0  0]
 [52  1  0 ...  0  0  0]
 [44  1  0 ...  0  0  0]
 ...
 [32  0  0 ...  0  0  0]
 [46  1  0 ...  0  0  0]
 [45  1  0 ...  0  0  0]] [0 1 1 ... 0 1 0]


In [26]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.996116504854369
